### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [Rodin-Anatoliy/project-work-10#1]
Здравствуйте. Благодарю за проделанную работу.
К сожалению, текущая версия содержит ряд недостатков не позволяющих мне засчиатать работу на данной итерации:

## Репозиторий
**Нужно исправить**: отсутствуют git-теги отражающие номер версии. Создать их можно при помощи команды `git tag -a v0.0.1 -m "my first version"`
Обращаю внимание что теги по-умолчанию не публикуются при вызове команды `git push`
Для их публикации выполните команду `git push origin --tags`
Подробнее: https://git-scm.com/book/ru/v2/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-Git-%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%BC%D0%B5%D1%82%D0%BA%D0%B0%D0%BC%D0%B8

### Email
**Нужно исправить** следующие корректные кейсы не проходят валидацию

`t2e-s_t@g-m2ail.academy` - адрес сайта может содержать длинную доменную зону. Я рекомендую убрать или значительно увеличить ограничение на длину доменной зоны

**Нужно исправить** следующие некорректные кейсы проходят валидацию:
`_@site.ru` - имя ящика не может состоять только из спецсимволов
`_some_@ya.ru` - имя ящика не может начинаться и заканчиваться на спецсимвол
`my---mail@site.ru` - адрес электронной почы, содержащий несколько символов '-' подряд является некорректным

### Адрес сайта
**Нужно исправить** Проверку проходят следующие некорректные адреса сайта
`http://www.ya.` - отсутствует доменная зона, точка на конце
`http://google.ru:/path/to/deep` - отсутствует номер порта после символа `:`
`http://127.0..`  - некорректный IP, точка на конце)
`http://127.0.0.1:8000/$ssss@#` - некоректный путь - разрешены только цифры, слешы и латинские буквы, решетка (#) на конце
`https://mysite.23` - tld не может состоять только из цифр

**Можно лучше** Проверку проходят следующие некорректные адреса сайта
`http://www.google.ru///////` - в пути количество слешей подряд должно быть ограничено 1

**Comment by Rodin-Anatoliy** [comment]
1) отсутствуют git-теги - **fixed**
2) email pattern - **fixed**
3) адрес сайта - **fixed**

**Comment by zlocate** [comment]
Добрый день
К сожалению пока есть кейсы по которым требуются правки

### Email
**Нужно исправить** следующий корректный кейс не проходит валидацию
`ya2@2ya.ru` - имя и домен могут содержать цифры (пример из текста задания)

**Comment by Rodin-Anatoliy** [comment]
Исправлено, pattern для **Email**, кейс `ya2@2ya.ru` - теперь валидный
